import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Proyecto Automatas 3er Parcial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <Head>
        {/* Add metadata to the head of the document */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>

    </>
  )
}
